---
remotes:
  vendor: https://github.com/defunkt/hub
  owner : git@github.com:destructuring/paul
  primary: https://github.com/destructuring/paul
  secondary: git@destructuring.org:destructuring/paul
